<?php
$z[0]=Array("field","",136,165);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",203,262);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",307,326);
$z[2][4]['name']="title";
$z[3]=Array("global","",327,353);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",1074,1109);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n      <a href='[field:typelink/]'>[field:typename/]</a>\r\n      ",1500,1676);
$z[5][4]['type']="sun";
$z[5][4]['currentstyle']="<a class='divxz' href='~typelink~' ~rel~>~typename~</a>";
$z[6]=Array("global","",1914,1931);
$z[6][4]['name']="qq";
$z[7]=Array("field","",2209,2238);
$z[7][4]['name']="typename";
$z[8]=Array("field","",2441,2460);
$z[8][4]['name']="title";
$z[9]=Array("field","",2506,2562);
$z[9][4]['name']="pubdate";
$z[9][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[10]=Array("field","",2618,2636);
$z[10][4]['name']="body";
$z[11]=Array("prenext","",2767,2792);
$z[11][4]['get']="pre";
$z[12]=Array("prenext","",2804,2830);
$z[12][4]['get']="next";
$z[13]=Array("include","",2897,2934);
$z[13][4]['filename']="footer.htm";

?>