<li> <a id="li0{dede:global name=itemindex runphp='yes'}@me=@me+1;{/dede:global}" class="navi navi_0{dede:global name=itemindex runphp='yes'}@me=@me+1;{/dede:global} " href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a>
          <ul id="ul0{dede:global name=itemindex runphp='yes'}@me=@me+1;{/dede:global}" class="sv sed_navi_0{dede:global name=itemindex runphp='yes'}@me=@me+1;{/dede:global}  hide">
            {dede:channel type='son' noself='yes'}
            <li> <a href="[field:typelink/]">[field:typename/]</a> </li>
            {/dede:channel}
          </ul>
        </li>