<?php
$z[0]=Array("global","@me=@me+1;",15,80);
$z[0][4]['name']="itemindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("global","@me=@me+1;",100,165);
$z[1][4]['name']="itemindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("field","",174,202);
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",204,233);
$z[3][4]['name']="typename";
$z[4]=Array("global","@me=@me+1;",260,325);
$z[4][4]['name']="itemindex";
$z[4][4]['runphp']="yes";
$z[5]=Array("global","@me=@me+1;",347,412);
$z[5][4]['name']="itemindex";
$z[5][4]['runphp']="yes";
$z[6]=Array("channel","\r\n            <li> <a href=\"[field:typelink/]\">[field:typename/]</a> </li>\r\n            ",434,575);
$z[6][4]['type']="son";
$z[6][4]['noself']="yes";

?>