<?php
$z[0]=Array("arcurl","",50,65);
$z[1]=Array("title","",123,137);
$z[2]=Array("picname","",144,160);
$z[3]=Array("pubdate","",194,239);
$z[3][4]['function']="MyDate('Y-m-d',@me)";
$z[4]=Array("arcurl","",255,270);
$z[5]=Array("title","",272,286);
$z[6]=Array("arcurl","",333,348);
$z[7]=Array("description","",351,401);
$z[7][4]['function']="cn_substr(@me,150)";
$z[8]=Array("arcurl","",447,462);

?>