<dl class="first">
    <dt class="tit"> <a href="[field:arcurl/]">
                    <img width="120" height="72" alt="[field:title/]" src="[field:picname/]"> </a>
                   <span>[field:pubdate function=MyDate('Y-m-d',@me)/]</span><a href="[field:arcurl/]">[field:title/]</a> 
    </dt>
    <dd class="des"><a href="[field:arcurl/]"> [field:description function="cn_substr(@me,150)"/]...</a></dd>
    <dd class="detail"><a href="[field:arcurl/]">详细内容 &gt;&gt;</a></dd>
  </dl>