<?php
$z[0]=Array("channelartlist","\r\n      <li>\r\n        <h5> <a rel=\"nofollow\" href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a> </h5>\r\n        <dl>\r\n          {dede:channel type='son' noself='yes'}\r\n          <dd> <a rel=\"nofollow\" href=\"[field:typelink/]\">[field:typename/]</a> </dd>\r\n          {/dede:channel}\r\n        </dl>\r\n      </li>\r\n      ",73,471);
$z[0][4]['typeid']="top";
$z[0][4]['row']="8";
$z[1]=Array("global","",553,575);
$z[1][4]['name']="dianhua";
$z[2]=Array("global","",698,715);
$z[2][4]['name']="qq";
$z[3]=Array("global","",1003,1029);
$z[3][4]['name']="cfg_powerby";

?>