<?php
$z[0]=Array("channelartlist","\r\n        <li> <a id=\"li0{dede:global name=itemindex runphp='yes'}@me=@me+1;{/dede:global}\" class=\"navi navi_0{dede:global name=itemindex runphp='yes'}@me=@me+1;{/dede:global} \" href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n          <ul id=\"ul0{dede:global name=itemindex runphp='yes'}@me=@me+1;{/dede:global}\" class=\"sv sed_navi_0{dede:global name=itemindex runphp='yes'}@me=@me+1;{/dede:global}  hide\">\r\n            {dede:channel type='son' noself='yes'}\r\n            <li> <a href=\"[field:typelink/]\">[field:typename/]</a> </li>\r\n            {/dede:channel}\r\n          </ul>\r\n        </li>\r\n        ",1886,2577);
$z[0][4]['typeid']="top";
$z[0][4]['row']="8";

?>