<?php
$z[0]=Array("field","",136,165);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",203,262);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",307,326);
$z[2][4]['name']="title";
$z[3]=Array("global","",327,353);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",1070,1105);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n      <a href='[field:typelink/]'>[field:typename/]</a>\r\n      ",1496,1672);
$z[5][4]['type']="sun";
$z[5][4]['currentstyle']="<a class='divxz' href='~typelink~' ~rel~>~typename~</a>";
$z[6]=Array("global","",1910,1927);
$z[6][4]['name']="qq";
$z[7]=Array("field","",2205,2234);
$z[7][4]['name']="typename";
$z[8]=Array("list","\r\n  <dl class=\"first\">\r\n    <dt class=\"tit\"> <a href=\"[field:arcurl/]\">\r\n                    <img width=\"120\" height=\"72\" alt=\"[field:title/]\" src=\"[field:picname/]\"> </a>\r\n                   <span>[field:pubdate function=MyDate('Y-m-d',@me)/]</span><a href=\"[field:arcurl/]\">[field:title/]</a> \r\n    </dt>\r\n    <dd class=\"des\"><a href=\"[field:arcurl/]\"> [field:description function=\"cn_substr(@me,150)\"/]...</a></dd>\r\n    <dd class=\"detail\"><a href=\"[field:arcurl/]\">详细内容 &gt;&gt;</a></dd>\r\n  </dl>\r\n ",2347,2907);
$z[8][4]['pagesize']="6";
$z[8][4]['titlelen']="40";
$z[9]=Array("pagelist","",2940,3011);
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",3074,3111);
$z[10][4]['filename']="footer.htm";

?>