<?php
$z[0]=Array("field","",136,165);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",203,262);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",307,326);
$z[2][4]['name']="title";
$z[3]=Array("global","",327,353);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",1072,1107);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n      <a href='[field:typelink/]'>[field:typename/]</a>\r\n      ",1501,1677);
$z[5][4]['type']="sun";
$z[5][4]['currentstyle']="<a class='divxz' href='~typelink~' ~rel~>~typename~</a>";
$z[6]=Array("global","",1917,1934);
$z[6][4]['name']="qq";
$z[7]=Array("field","",2327,2348);
$z[7][4]['name']="content";
$z[8]=Array("include","",2396,2433);
$z[8][4]['filename']="footer.htm";

?>